export const MESSAGE_REQUEST = "MESSAGE_REQUEST";
export const MESSAGE_REQUEST_SUCCEEDED = "MESSAGE_REQUEST_SUCCEEDED";
export const MESSAGE_REQUEST_FAILED = "MESSAGE_REQUEST_FAILED";

export const MESSAGE_CREATE_REQUEST = "MESSAGE_CREATE_REQUEST";
export const MESSAGE_CREATE_REQUEST_SUCCEEDED =
  "MESSAGE_CREATE_REQUEST_SUCCEEDED";
export const MESSAGE_CREATE_REQUEST_FAILED = "MESSAGE_CREATE_REQUEST_FAILED";

export const MESSAGE_DELETE_REQUEST = "MESSAGE_DELETE_REQUEST";
export const MESSAGE_DELETE_REQUEST_SUCCEEDED =
  "MESSAGE_DELETE_REQUEST_SUCCEEDED";
export const MESSAGE_DELETE_REQUEST_FAILED = "MESSAGE_DELETE_REQUEST_FAILED";
